spring.datasource.url=jdbc:postgresql://dpg-d6tvggvgi27c73duukp0-a.oregon-postgres.render.com:5432/db_deploy_gs_luanbasani
spring.datasource.username=db_deploy_gs_luanbasani_user
spring.datasource.password=${DB_PASSWORD}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect